# generated by zon2nix (https://github.com/nix-community/zon2nix)

{ linkFarm, fetchzip, fetchgit }:

linkFarm "zig-packages" [
  {
    name = "N-V-__8AAHEsCACb_b9D1HnCysDKIhKFOrITbxYh9JRh9ix5";
    path = fetchgit {
      url = "https://github.com/LMDB/lmdb";
      rev = "ce201088de95d26fc0da36ba805bf2ddc2ba74ff";
      hash = "sha256-gQdu0PNHd2y9LC6aUVl2Bm3j9XjlBI5oDY73ae5H9VU=";
    };
  }
  {
    name = "N-V-__8AAO1SWwCbwhTAU7t6L3XQtTy6TzE8CiOGHjENn_rl";
    path = fetchgit {
      url = "https://github.com/bitcoin-core/secp256k1";
      rev = "1a53f4961f337b4d166c25fce72ef0dc88806618";
      hash = "sha256-DnBgetf+98n7B1JGtyTdxyc+yQ51A3+ueTIPPSWCm4E=";
    };
  }
  {
    name = "native_sdk-0.1.0-hzDzQjHj7QFUR4i8PUurrKO7eqKXKGGNmRduN3Mq_E9R";
    path = fetchgit {
      url = "https://github.com/sepehr-safari/native";
      rev = "55ab7392285e0473dee0e579418dd5b21147b1e6";
      hash = "sha256-BDPnnrqo8Lh+U6BArG4wdoPz1X/olK+5+0mEa92qlSg=";
    };
  }
  {
    name = "nostr-0.3.8-CMyPzfkiBwCitoR2x0Wt612ODfR3JXqYEjmTGW9axBRm";
    path = fetchzip {
      url = "https://codeload.github.com/zig-nostr/nostr/tar.gz/refs/tags/v0.3.8";
      hash = "sha256-s5LHqFhKFUybrnjttM1FP9GM47CGTSc33DAWunLTV98=";
    };
  }
  {
    name = "zg-0.16.2-oGqU3HqftgI6rwFS90ypwfjgToH8Pz829OKuFURlm773";
    path = fetchzip {
      url = "https://codeberg.org/atman/zg/archive/v0.16.2.tar.gz";
      hash = "sha256-YeLHpMVSyzhe8uvh9uIiEhdSLhQuE8DEQDsHjuDycYY=";
    };
  }
]
